name: MMRouting
channels:
  - conda-forge
  - defaults
dependencies:
  - folium=0.10.1=py_0
  - geopandas=0.7.0=py_1
  - networkx=2.4=py_1
  - numpy=1.18.1=py38hc71023c_0
  - osmnx=0.12=pyh9f0ad1d_0
  - pandas=1.0.2=py38hbe40bda_0
  - pip=20.0.2=py_2
  - pyproj=2.6.0=py38hff69d4a_0
  - requests=2.23.0=pyh8c360ce_2
  - scikit-learn=0.22.2.post1=py38h7208079_0
  - scipy=1.3.2=py38h582fac2_0
  - pip:
    - colorhash==1.0.2
    - ortools==7.5.7466

